server:
  port: 8888

app:
  keycloak-admin:
    base-url: http://keycloak:8080
    realm: ai-recruitment
    client-id: hireAI-backend
    client-secret: ${KC_BACKEND_CLIENT_SECRET}

  messaging:
    exchange: ai-recruitment.exchange

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://keycloak:8080/realms/ai-recruitment/protocol/openid-connect/certs

  cloud:
    discovery:
      enabled: true

    gateway:
      routes:
        - id: application-microservice
          uri: lb://application-microservice
          predicates:
            - Path=/api/applications/**

        - id: job-microservice
          uri: lb://job-microservice
          predicates:
            - Path=/api/jobs/**

      server:
        webflux:
          discovery:
            locator:
              enabled: false

      globalcors:
        corsConfigurations:
          "[/**]":
            allowedOrigins:
              - http://localhost:4200
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders:
              - Authorization
              - Content-Type
            allowCredentials: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    gateway:
      access: unrestricted

eureka:
  client:
    register-with-eureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka
  instance:
    prefer-ip-address: true

resilience4j:
  circuitbreaker:
    configs:
      default:
        slidingWindowSize: 10
        permittedNumberOfCallsInHalfOpenState: 2
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
